### PR TITLE
Gareth add sort command testing

### PR DESCRIPTION
**Pull request by GarethOng**
**SortCommandTesting**
- test sorting list by names in ascending order
- test sorting list by names in descending order
- test sorting list of professors by name in ascending order
- test sorting list of students by name in ascending order
- test sorting list of teaching assistants by name in ascending order

**OrderTesting**
- test creating increasing order from string
- test creating deceasing order from string
- test equals

Any suggestions for ways to test the sort function?

### CODE REVIEW

**Review by Jonaspng — APPROVED** [review]
LGTM. But why did your code coverage decrease?

**Review by nitant-p — APPROVED** [review]
LGTM!

**Review by JJoeYi — COMMENTED** [review]
LGTM

**Review by normkoh — COMMENTED** [review]
LGTM!

**Pull request merged**
