### PR TITLE
Normkoh pie chart

### LINKED ISSUE #92: As a student, I want to visualise the data in my contacts list in a pie chart, so that I can have a quick overview of my network

### PR DESCRIPTION
**Pull request by normkoh**
Fixes #92 

Added a pie Chart to the right of the contact list to visualise spread of students, professors and TAs.

The image below shows how the Ui looks like.
image

### CODE REVIEW

**Review by Jonaspng — APPROVED** [review]
LGTM. However, you could add numbers on the pie chart to indicate how many profs ta and students there are. 
Furthremore, Please create an user story and put it in github issues. The user story will be used to substantiate why we need a pie chart as one of the features.

**Comment by nitant-p** [comment]
LGTM! Also will the pie chart always be shown? Maybe users can type in a command to display it instead of it being on display by default. 

What do the others think?

**Comment by normkoh** [comment]
Sounds good! I think we could definitely consider it as a possible enhancement.

Do you think a command such as `show` and `hide` to toggle between showing and hiding the pie chart would be better, or just a `show` command that shows the pie chart for the current list of contacts, and auto hides itself after once the list is modified?

What do the rest think?

**Comment by Jonaspng** [comment]
I think this feature does not affect user experience much and should only be added if and when we have time. 

To answer your question @normkoh I think the first option that you stated would be better choice as it would be easier to implement.

I think a more important point that we should be addressing is whether the amount of space given to pie chart should scale with screen size or we make it fixed.

@normkoh if you feel overwhelmed due to your current work load, do not attempt this enhancement suggested by @nitant-p. Or you could assign it to the rest of us to do. Do let us know if you need any help.

**Comment by nitant-p** [comment]
@normkoh I agree with @Jonaspng. it was only a minor suggestion, completely up to you whether to implement or not. 

As for the implementation, I think the first one is better and would also be easier to implement.

**Review by JJoeYi — COMMENTED** [review]
Looks great! LGTM

**Pull request merged**
